"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, Save, UserRound } from "lucide-react";
import { AdminShell } from "../../../components/dashboard-shell";
import { Button, Card, Input } from "../../../components/ui";

type Account = { name: string; email: string; role: string };
export default function AdminSettings() {
  const [account, setAccount] = useState<Account>({ name: "", email: "", role: "ADMIN" }); const [password, setPassword] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/admin/account").then(r => r.json()).then(result => { if (result.data) setAccount(result.data); else setNotice(result.error || "Gagal memuat akun."); }).catch(() => setNotice("Gagal memuat akun.")); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setNotice(""); const response = await fetch("/api/admin/account", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...account, password }) }); const result = await response.json().catch(() => ({})); setNotice(response.ok ? "Pengaturan akun berhasil disimpan." : result.error || "Pengaturan gagal disimpan."); if (response.ok) setPassword(""); setSaving(false); };
  return <AdminShell><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Admin workspace</p><h1 className="mt-2 font-display text-4xl">Pengaturan akun</h1><p className="mt-2 text-sm text-stone-500">Ubah identitas dan keamanan akun admin.</p>{notice && <p className="mt-5 rounded-lg bg-stone-100 p-3 text-sm text-stone-700">{notice}</p>}<form className="mt-8 space-y-5" onSubmit={save}><Card className="p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-2.5 text-gold"><UserRound size={18}/></div><div><h2 className="font-bold">Profil admin</h2><p className="mt-1 text-xs text-stone-500">Role: {account.role}</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Nama<Input className="mt-2" value={account.name} onChange={e => setAccount(current => ({ ...current, name: e.target.value }))} required/></label><label className="text-sm font-semibold">Email<Input className="mt-2" type="email" value={account.email} onChange={e => setAccount(current => ({ ...current, email: e.target.value }))} required/></label></div></Card><Card className="p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-stone-100 p-2.5 text-stone-600"><KeyRound size={18}/></div><div><h2 className="font-bold">Password</h2><p className="mt-1 text-xs text-stone-500">Isi hanya bila ingin mengganti password.</p></div></div><label className="mt-6 block text-sm font-semibold">Password baru<Input className="mt-2" type="password" minLength={8} placeholder="Minimal 8 karakter" value={password} onChange={e => setPassword(e.target.value)}/></label></Card><Button disabled={saving} className="bg-ink text-white"><Save size={15}/>{saving ? "Menyimpan..." : "Simpan perubahan"}</Button></form></div></AdminShell>;
}
