"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useEffect, useState } from "react";
import { Activity, ArrowUpRight, RefreshCw, Settings, Share2, Users } from "lucide-react";
import { AdminShell } from "../../components/dashboard-shell";
import { Badge, Button, Card } from "../../components/ui";
type Stats = { clients: number; invitations: number; rsvp: number; views: number; projects: { id: string; name: string; coupleName: string; status: string; updatedAt: number }[] };
export default function AdminDashboard() { const [stats, setStats] = useState<Stats | null>(null); const [error, setError] = useState(""); const load = async () => { const response = await fetch("/api/admin/stats"); const result = await response.json(); if (response.ok) setStats(result.data); else setError(result.error || "Gagal memuat statistik."); }; useEffect(() => { void load(); }, []); return <AdminShell><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Admin workspace</p><h1 className="mt-2 font-display text-4xl">Overview</h1><p className="mt-2 text-sm text-stone-500">Pantau seluruh aktivitas Kykastory.</p></div><div className="flex gap-2"><Button className="border border-stone-200 bg-white" onClick={() => void load()}><RefreshCw size={14}/> Refresh</Button><Link href="/admin/settings"><Button className="bg-ink text-white"><Settings size={14}/> Pengaturan</Button></Link></div></div>{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><K label="Total clients" value={stats?.clients ?? 0} icon={Users}/><K label="Active invitations" value={stats?.invitations ?? 0} icon={Share2}/><K label="Total RSVP" value={stats?.rsvp ?? 0} icon={Activity}/><K label="Views bulan ini" value={stats?.views ?? 0} icon={ArrowUpRight}/></div><Card className="mt-8 overflow-hidden"><div className="border-b border-stone-100 p-5 text-sm font-bold">Project terbaru</div>{stats?.projects.length ? stats.projects.map(project => <div className="flex items-center gap-4 border-b border-stone-100 p-5 last:border-0" key={project.id}><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-sand"><Share2 size={17}/></div><div className="flex-1"><p className="text-sm font-bold">{project.coupleName}</p><p className="mt-1 text-xs text-stone-400">{project.name} · diperbarui {new Date(project.updatedAt).toLocaleDateString("id-ID")}</p></div><Badge tone={project.status === "ACTIVE" ? "green" : "neutral"}>{project.status}</Badge></div>) : <div className="p-10 text-center text-sm text-stone-500">Belum ada project.</div>}</Card></AdminShell>; }
function K({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Users }) { return <Card className="p-5"><Icon size={18} className="text-gold"/><p className="mt-5 text-xs text-stone-500">{label}</p><p className="mt-1 text-3xl font-bold">{value.toLocaleString("id-ID")}</p></Card>; }
