"use client";
import { useEffect, useState } from "react";
import { Check, Image as ImageIcon, Save, Share2 } from "lucide-react";
import { AdminShell } from "../../../components/dashboard-shell";
import { Badge, Button, Card, Input } from "../../../components/ui";

const fallback = "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80";

export default function Projects() {
  const [imageUrl, setImageUrl] = useState(fallback), [saved, setSaved] = useState(false), [error, setError] = useState("");
  useEffect(() => { fetch("/api/projects/demo-project").then(r => r.json()).then(r => r.data?.coverImageUrl && setImageUrl(r.data.coverImageUrl)); }, []);
  async function save() { setError(""); const response = await fetch("/api/projects/demo-project", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ coverImageUrl: imageUrl }) }); const result = await response.json(); if (!response.ok) { setError(result.error || "Gagal menyimpan thumbnail"); return; } setSaved(true); setTimeout(() => setSaved(false), 2500); }
  return <AdminShell><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Administration</p><h1 className="mt-2 font-display text-4xl">Invitations</h1><p className="mt-2 text-sm text-stone-500">Kelola project dan tampilan dashboard client.</p></div><Button className="w-fit bg-ink text-white"><Share2 size={15}/> Tambah project</Button></div><Card className="mt-8 overflow-hidden"><div className="border-b border-stone-100 p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-2.5 text-gold"><ImageIcon size={18}/></div><div><h2 className="font-bold">Thumbnail dashboard client</h2><p className="mt-1 text-xs text-stone-500">Gambar ini ditampilkan pada kartu undangan di dashboard client.</p></div></div></div><div className="grid gap-6 p-6 lg:grid-cols-[1fr_280px]"><div><label className="text-sm font-semibold">URL gambar thumbnail<Input className="mt-2" value={imageUrl} onChange={e => { setImageUrl(e.target.value); setSaved(false); }} placeholder="https://..."/></label><p className="mt-3 text-xs leading-5 text-stone-400">Gunakan URL gambar publik dengan format JPG, PNG, atau WebP. Perubahan akan terlihat setelah client membuka ulang dashboard.</p>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}<Button className="mt-5 bg-ink text-white" onClick={save}><Save size={15}/>{saved ? "Tersimpan" : "Simpan thumbnail"}</Button></div><div><div className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-stone-100">{imageUrl ? <img src={imageUrl} alt="Preview thumbnail" className="h-full w-full object-cover" onError={e => { e.currentTarget.style.display = "none"; }}/>:<div className="flex h-full items-center justify-center text-xs text-stone-400">Belum ada gambar</div>}<div className="absolute left-3 top-3"><Badge tone="green"><Check size={11}/> Preview</Badge></div></div><p className="mt-3 text-center text-xs font-semibold text-stone-500">Wedding Chika & Fariz</p></div></div></Card></AdminShell>;
}
