"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, Image as ImageIcon, Save, Settings2, Trash2 } from "lucide-react";
import { AdminShell } from "../../../components/dashboard-shell";
import { Button, Card, Input } from "../../../components/ui";

type Client = { id: string; name: string; email: string };
type Project = { id: string; name: string; coupleName: string; slug: string; eventDate: string; invitationUrl: string; coverImageUrl: string | null; wordpressPostId: number | null; wordpressUrl: string | null; weddingpressSyncUrl: string | null; clients: Client[] };
const empty = { name: "", coupleName: "", slug: "", eventDate: "", invitationUrl: "", coverImageUrl: "", wordpressPostId: "", wordpressUrl: "", weddingpressSyncUrl: "", clientId: "" };

export default function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]), [clients, setClients] = useState<Client[]>([]), [selected, setSelected] = useState<Project | null>(null), [form, setForm] = useState(empty), [message, setMessage] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([fetch("/api/admin/projects").then(r => r.json()), fetch("/api/admin/clients").then(r => r.json())]).then(([p, c]) => { setProjects(p.data || []); setClients(c.data || []); const first = p.data?.[0]; if (first) selectProject(first); }).catch(() => setError("Gagal memuat project.")); }, []);
  function selectProject(project: Project) { setSelected(project); setForm({ name: project.name, coupleName: project.coupleName, slug: project.slug, eventDate: project.eventDate, invitationUrl: project.invitationUrl, coverImageUrl: project.coverImageUrl || "", wordpressPostId: project.wordpressPostId?.toString() || "", wordpressUrl: project.wordpressUrl || "", weddingpressSyncUrl: project.weddingpressSyncUrl || "", clientId: project.clients[0]?.id || "" }); setMessage(""); }
  function change(key: keyof typeof empty, value: string) { setForm(current => ({ ...current, [key]: value })); setMessage(""); }
  async function save(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(""); const response = await fetch(`/api/admin/projects/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Project gagal disimpan."); else { setMessage("Project berhasil disimpan."); const refreshed = await fetch("/api/admin/projects").then(r => r.json()); setProjects(refreshed.data || []); const next = (refreshed.data || []).find((item: Project) => item.id === selected.id); if (next) selectProject(next); } setSaving(false); }
  async function createProject() { const response = await fetch("/api/admin/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Project Baru", coupleName: "Nama Pasangan", slug: `project-${Date.now()}`, eventDate: new Date().toISOString().slice(0, 10) }) }); const result = await response.json(); if (!response.ok) setError(result.error || "Project gagal dibuat."); else { setProjects(current => [...current, { ...result.data, clients: [] }]); selectProject({ ...result.data, clients: [] }); } }
  async function deleteProject() { if (!selected || !window.confirm(`Hapus project ${selected.coupleName}?`)) return; const response = await fetch(`/api/admin/projects/${selected.id}`, { method: "DELETE" }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Project gagal dihapus."); else { const remaining = projects.filter(project => project.id !== selected.id); setProjects(remaining); setSelected(remaining[0] || null); if (remaining[0]) selectProject(remaining[0]); setMessage("Project berhasil dihapus."); } }
  return <AdminShell><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Administration</p><h1 className="mt-2 font-display text-4xl">Invitations</h1><p className="mt-2 text-sm text-stone-500">Kelola project, client, thumbnail, dan integrasi WeddingPress.</p></div><Button className="w-fit bg-ink text-white" onClick={() => void createProject()}>+ Tambah project</Button></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[280px_1fr]"><Card className="h-fit overflow-hidden"><p className="border-b border-stone-100 p-5 text-sm font-bold">Project</p>{projects.map(project => <button key={project.id} onClick={() => selectProject(project)} className={`block w-full border-b border-stone-100 p-4 text-left last:border-0 ${selected?.id === project.id ? "bg-stone-50" : "hover:bg-stone-50"}`}><p className="text-sm font-bold">{project.coupleName}</p><p className="mt-1 text-xs text-stone-500">{project.clients[0]?.name || "Belum di-assign"}</p><p className="mt-1 truncate font-mono text-[10px] text-stone-400">ID: {project.id}</p></button>)}</Card>
      <Card className="overflow-hidden"><div className="border-b border-stone-100 p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-2.5 text-gold"><Settings2 size={18}/></div><div><h2 className="font-bold">Pengaturan project</h2><p className="mt-1 text-xs text-stone-500">Perubahan langsung tersimpan ke database production.</p></div></div></div>{selected ? <form className="space-y-6 p-6" onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Nama project<Input className="mt-2" value={form.name} onChange={e => change("name", e.target.value)} required/></label><label className="text-sm font-semibold">Nama pasangan<Input className="mt-2" value={form.coupleName} onChange={e => change("coupleName", e.target.value)} required/></label><label className="text-sm font-semibold">Slug<Input className="mt-2" value={form.slug} onChange={e => change("slug", e.target.value)} required/></label><label className="text-sm font-semibold">Tanggal acara<Input className="mt-2" type="date" value={form.eventDate} onChange={e => change("eventDate", e.target.value)} required/></label><label className="text-sm font-semibold sm:col-span-2">Client pemilik<select className="mt-2 h-10 w-full rounded-xl border border-stone-200 bg-white px-3 text-sm" value={form.clientId} onChange={e => change("clientId", e.target.value)}><option value="">Belum di-assign</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name} — {client.email}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2">URL undangan<Input className="mt-2" value={form.invitationUrl} onChange={e => change("invitationUrl", e.target.value)} /></label><label className="text-sm font-semibold sm:col-span-2">URL thumbnail<Input className="mt-2" value={form.coverImageUrl} onChange={e => change("coverImageUrl", e.target.value)} placeholder="https://..." /></label></div>
          <div className="rounded-2xl bg-stone-50 p-5"><p className="text-sm font-bold">Integrasi WordPress / WeddingPress</p><p className="mt-1 text-xs text-stone-500">Simpan Post ID untuk referensi bridge dan URL sync webhook dari WeddingPress.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">WordPress Post ID<Input className="mt-2" type="number" value={form.wordpressPostId} onChange={e => change("wordpressPostId", e.target.value)} placeholder="277" /></label><label className="text-sm font-semibold">WordPress URL<Input className="mt-2" value={form.wordpressUrl} onChange={e => change("wordpressUrl", e.target.value)} placeholder="https://domain.com" /></label><label className="text-sm font-semibold sm:col-span-2">WeddingPress Sync URL<Input className="mt-2" value={form.weddingpressSyncUrl} onChange={e => change("weddingpressSyncUrl", e.target.value)} placeholder="https://domain.com/wp-json/..." /></label></div></div>
          {error && <p className="rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}{message && <p className="rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700">{message}</p>}<div className="flex flex-wrap gap-2"><Button disabled={saving} className="bg-ink text-white"><Save size={15}/>{saving ? "Menyimpan..." : "Simpan pengaturan"}</Button><Button type="button" className="border border-red-200 text-red-600" onClick={() => void deleteProject()}><Trash2 size={15}/> Hapus project</Button></div></form> : <div className="p-10 text-center text-sm text-stone-500">Pilih project untuk mengedit.</div>}</Card></div>
    {selected && form.coverImageUrl && <div className="mt-6 flex items-center gap-4 text-xs text-stone-500"><div className="relative h-16 w-24 overflow-hidden rounded-xl"><img src={form.coverImageUrl} alt="Preview thumbnail" className="h-full w-full object-cover" /></div><span><Check size={13} className="mr-1 inline text-emerald-600"/> Thumbnail aktif untuk dashboard client</span><ImageIcon size={16} className="ml-auto text-stone-300"/></div>}
  </AdminShell>;
}
