import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";
import { existsSync, mkdirSync } from "fs";
import path from "path";

const dataDir = path.join(process.cwd(), "data");
if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });
export const sqlite = new Database(path.join(dataDir, "kykastory.db"));
sqlite.pragma("journal_mode = WAL");
export const db = drizzle(sqlite, { schema });

export function ensureDatabase() {
  const userColumns = sqlite.prepare("PRAGMA table_info(user)").all() as { name: string }[];
  if (userColumns.some(column => column.name === "email_verified")) sqlite.exec("ALTER TABLE user RENAME COLUMN email_verified TO emailVerified; ALTER TABLE user RENAME COLUMN created_at TO createdAt; ALTER TABLE user RENAME COLUMN updated_at TO updatedAt;");
  const sessionColumns = sqlite.prepare("PRAGMA table_info(session)").all() as { name: string }[];
  if (sessionColumns.some(column => column.name === "expires_at")) sqlite.exec("ALTER TABLE session RENAME COLUMN expires_at TO expiresAt; ALTER TABLE session RENAME COLUMN created_at TO createdAt; ALTER TABLE session RENAME COLUMN updated_at TO updatedAt; ALTER TABLE session RENAME COLUMN ip_address TO ipAddress; ALTER TABLE session RENAME COLUMN user_agent TO userAgent; ALTER TABLE session RENAME COLUMN user_id TO userId;");
  const accountColumns = sqlite.prepare("PRAGMA table_info(account)").all() as { name: string }[];
  if (accountColumns.some(column => column.name === "account_id")) sqlite.exec("ALTER TABLE account RENAME COLUMN account_id TO accountId; ALTER TABLE account RENAME COLUMN provider_id TO providerId; ALTER TABLE account RENAME COLUMN user_id TO userId; ALTER TABLE account RENAME COLUMN access_token TO accessToken; ALTER TABLE account RENAME COLUMN refresh_token TO refreshToken; ALTER TABLE account RENAME COLUMN id_token TO idToken; ALTER TABLE account RENAME COLUMN access_token_expires_at TO accessTokenExpiresAt; ALTER TABLE account RENAME COLUMN refresh_token_expires_at TO refreshTokenExpiresAt; ALTER TABLE account RENAME COLUMN created_at TO createdAt; ALTER TABLE account RENAME COLUMN updated_at TO updatedAt;");
  sqlite.exec(`CREATE TABLE IF NOT EXISTS user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, emailVerified INTEGER NOT NULL DEFAULT 0, image TEXT, role TEXT NOT NULL DEFAULT 'CLIENT', createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS session (id TEXT PRIMARY KEY, expiresAt INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, ipAddress TEXT, userAgent TEXT, userId TEXT NOT NULL); CREATE TABLE IF NOT EXISTS account (id TEXT PRIMARY KEY, accountId TEXT NOT NULL, providerId TEXT NOT NULL, userId TEXT NOT NULL, accessToken TEXT, refreshToken TEXT, idToken TEXT, accessTokenExpiresAt INTEGER, refreshTokenExpiresAt INTEGER, scope TEXT, password TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expiresAt INTEGER NOT NULL, createdAt INTEGER, updatedAt INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL, couple_name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, event_date TEXT NOT NULL, invitation_url TEXT NOT NULL, cover_image_url TEXT, wordpress_post_id INTEGER, wordpress_url TEXT, weddingpress_sync_url TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS project_members (project_id TEXT NOT NULL, user_id TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(project_id, user_id)); CREATE TABLE IF NOT EXISTS guests (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL, category TEXT, seat_count INTEGER NOT NULL DEFAULT 1, slug TEXT NOT NULL, delivery_status TEXT NOT NULL DEFAULT 'NOT_SENT', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS rsvps (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT NOT NULL, guest_name TEXT NOT NULL, attendance_status TEXT NOT NULL, guest_count INTEGER NOT NULL DEFAULT 1, message TEXT NOT NULL DEFAULT '', submitted_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS message_templates (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT NOT NULL, name TEXT NOT NULL, content TEXT NOT NULL, is_default INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);`);
  const projectColumns = sqlite.prepare("PRAGMA table_info(projects)").all() as { name: string }[];
  if (!projectColumns.some(column => column.name === "wordpress_post_id")) sqlite.exec("ALTER TABLE projects ADD COLUMN wordpress_post_id INTEGER;");
  if (!projectColumns.some(column => column.name === "wordpress_url")) sqlite.exec("ALTER TABLE projects ADD COLUMN wordpress_url TEXT;");
  if (!projectColumns.some(column => column.name === "weddingpress_sync_url")) sqlite.exec("ALTER TABLE projects ADD COLUMN weddingpress_sync_url TEXT;");
}
