import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: integer("email_verified", { mode: "boolean" }).notNull().default(false), image: text("image"), role: text("role").notNull().default("CLIENT"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() });
export const sessions = sqliteTable("session", { id: text("id").primaryKey(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), token: text("token").notNull().unique(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull() });
export const accounts = sqliteTable("account", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull(), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: integer("access_token_expires_at", { mode: "timestamp_ms" }), refreshTokenExpiresAt: integer("refresh_token_expires_at", { mode: "timestamp_ms" }), scope: text("scope"), password: text("password"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() });
export const verifications = sqliteTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }), updatedAt: integer("updated_at", { mode: "timestamp_ms" }) });
export const projects = sqliteTable("projects", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), name: text("name").notNull(), coupleName: text("couple_name").notNull(), slug: text("slug").notNull().unique(), eventDate: text("event_date").notNull(), invitationUrl: text("invitation_url").notNull(), coverImageUrl: text("cover_image_url"), wordpressPostId: integer("wordpress_post_id"), wordpressUrl: text("wordpress_url"), weddingpressSyncUrl: text("weddingpress_sync_url"), status: text("status").notNull().default("ACTIVE"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() });
export const projectMembers = sqliteTable("project_members", { projectId: text("project_id").notNull(), userId: text("user_id").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() });
export const webhookLogs = sqliteTable("webhook_logs", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: text("project_id").notNull(), source: text("source").notNull(), status: text("status").notNull(), imported: integer("imported").notNull().default(0), message: text("message").notNull().default(""), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() });
export const guests = sqliteTable("guests", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: text("project_id").notNull(), name: text("name").notNull(), phone: text("phone").notNull(), category: text("category"), seatCount: integer("seat_count").notNull().default(1), slug: text("slug").notNull(), deliveryStatus: text("delivery_status").notNull().default("NOT_SENT"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() });
export const rsvps = sqliteTable("rsvps", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: text("project_id").notNull(), guestName: text("guest_name").notNull(), attendanceStatus: text("attendance_status").notNull(), guestCount: integer("guest_count").notNull().default(1), message: text("message").notNull().default(""), submittedAt: integer("submitted_at", { mode: "timestamp_ms" }).notNull() });
export const messageTemplates = sqliteTable("message_templates", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: text("project_id").notNull(), name: text("name").notNull(), content: text("content").notNull(), isDefault: integer("is_default", { mode: "boolean" }).notNull().default(true), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() });
