"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { Button, Input } from "../../components/ui";

export default function Login() {
  const router = useRouter();
  const [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/auth/sign-in/email", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); if (response.ok) { const adminCheck = await fetch("/api/admin/account"); router.replace(adminCheck.ok ? "/admin" : "/dashboard"); } else { const body = await response.json().catch(() => null); setError(body?.message || "Email atau password salah."); setLoading(false); } }
  return <main className="flex min-h-screen bg-white"><div className="hidden w-1/2 bg-[#201d19] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="font-display text-2xl">kykastory<span className="text-gold">.</span></div><div className="max-w-md"><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-gold">Your story, beautifully shared</p><h1 className="font-display text-6xl leading-[1.05]">Make every moment <i className="font-normal text-[#d5bc96]">memorable.</i></h1><p className="mt-7 text-sm leading-7 text-stone-400">Kelola undangan, bagikan kabar bahagia, dan lihat ucapan dari orang-orang tersayang dalam satu tempat.</p></div><p className="text-xs text-stone-500">© 2026 Kykastory</p></div><div className="flex flex-1 items-center justify-center p-6"><div className="w-full max-w-[390px]"><div className="mb-10 font-display text-2xl lg:hidden">kykastory<span className="text-gold">.</span></div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Welcome back</p><h2 className="mt-3 font-display text-4xl">Masuk ke akunmu</h2><p className="mt-3 text-sm text-stone-500">Kelola momen istimewa bersama Kykastory.</p><form className="mt-9 space-y-5" onSubmit={submit}><label className="block text-sm font-semibold">Email<Input name="email" className="mt-2" type="email" placeholder="nama@email.com" required/></label><label className="block text-sm font-semibold">Password<div className="relative mt-2"><Input name="password" className="pr-10" type="password" placeholder="••••••••" required/><LockKeyhole size={16} className="absolute right-3 top-3 text-stone-400"/></div></label>{error&&<p className="rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}<Button disabled={loading} type="submit" className="h-12 w-full bg-ink text-white">{loading?"Memeriksa...":"Masuk"} {!loading&&<ArrowRight size={16}/>}</Button></form><p className="mt-8 text-center text-xs text-stone-500">Belum punya akun? <span className="font-bold text-ink">Hubungi admin Kykastory</span></p></div></div></main>;
}
