"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, CheckCircle2, Clipboard, ExternalLink, RefreshCw, Send, Settings2, Wifi } from "lucide-react";
import { useRouter } from "next/navigation";
import { AdminShell } from "../../../components/dashboard-shell";
import { Badge, Button, Card } from "../../../components/ui";

type Project = { id: string; coupleName: string; wordpressPostId: number | null; wordpressUrl: string | null; weddingpressSyncUrl: string | null };
type Log = { id: number; projectId: string; source: string; status: string; imported: number; message: string; createdAt: number };

export default function Integrations() {
  const router = useRouter();
  const [projects, setProjects] = useState<Project[]>([]), [selected, setSelected] = useState(""), [payload, setPayload] = useState('{"rsvps":[{"name":"Demo WeddingPress","status":"HADIR","guestCount":2,"message":"Selamat!"}]}'), [notice, setNotice] = useState(""), [logs, setLogs] = useState<Log[]>([]), [copied, setCopied] = useState("");
  const loadLogs = () => fetch("/api/admin/integrations/logs").then(r => r.json()).then(r => setLogs(r.data || []));
  useEffect(() => { fetch("/api/admin/projects").then(r => r.json()).then(r => { setProjects(r.data || []); if (r.data?.[0]) setSelected(r.data[0].id); }); void loadLogs(); const timer = window.setInterval(() => void loadLogs(), 30000); return () => window.clearInterval(timer); }, []);
  const project = projects.find(p => p.id === selected);
  const endpoint = `https://id.kykastory.com/api/projects/${selected || "PROJECT_ID"}/rsvp/sync`;
  const copy = async (value: string, label: string) => { await navigator.clipboard?.writeText(value); setCopied(label); window.setTimeout(() => setCopied(""), 1800); };
  const testSync = async () => { try { const response = await fetch(`/api/projects/${selected}/rsvp/sync`, { method: "POST", headers: { "Content-Type": "application/json" }, body: payload }); const result = await response.json(); setNotice(response.ok ? `${result.imported} RSVP berhasil diterima.` : result.error || "Sync gagal."); void loadLogs(); } catch { setNotice("Payload JSON tidak valid."); } };
  const projectLogs = useMemo(() => logs.filter(log => !selected || log.projectId === selected), [logs, selected]);
  return <AdminShell><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">System</p><h1 className="mt-2 font-display text-4xl">Integrations</h1><p className="mt-2 text-sm text-stone-500">Kelola koneksi bridge WordPress dan pantau RSVP masuk.</p></div><Badge tone="green"><span className="mr-1 h-1.5 w-1.5 rounded-full bg-emerald-500"/> Auto sync aktif</Badge></div>
    <Card className="mt-8 overflow-hidden"><div className="flex flex-col gap-4 border-b border-stone-100 bg-stone-50/70 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-gold">Project aktif</p><h2 className="mt-1 text-lg font-bold">{project?.coupleName || "Memuat project..."}</h2><p className="mt-1 font-mono text-xs text-stone-500">{selected || "-"}</p></div><select className="h-10 rounded-xl border border-stone-200 bg-white px-3 text-sm" value={selected} onChange={e => setSelected(e.target.value)}>{projects.map(p => <option key={p.id} value={p.id}>{p.coupleName}</option>)}</select></div><div className="grid gap-5 p-6 lg:grid-cols-2"><div><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2.5 text-emerald-600"><Wifi size={18}/></div><div><h3 className="font-bold">WeddingPress Bridge</h3><p className="text-xs text-stone-500">RSVP baru dikirim otomatis saat form Guestbook dikirim.</p></div></div><div className="mt-6 space-y-3"><InfoRow label="Status" value="Terhubung · menunggu webhook" tone="green"/><InfoRow label="WordPress Post ID" value={project?.wordpressPostId?.toString() || "Belum diatur"}/><InfoRow label="Form ID" value="Diatur di WordPress Bridge"/></div></div><div className="rounded-2xl bg-ink p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.15em] text-gold">Endpoint project</p><p className="mt-3 break-all font-mono text-xs leading-5 text-stone-300">{endpoint}</p><Button className="mt-4 bg-white text-ink" onClick={() => void copy(endpoint, "endpoint")}><Clipboard size={14}/>{copied === "endpoint" ? "Tersalin" : "Salin endpoint"}</Button><p className="mt-4 text-[11px] leading-5 text-stone-400">Header: <code className="text-stone-200">x-weddingpress-secret</code></p></div></div></Card>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-2.5 text-gold"><Settings2 size={18}/></div><div><h2 className="font-bold">Checklist konfigurasi</h2><p className="mt-1 text-xs text-stone-500">Ikuti urutan ini untuk setiap undangan.</p></div></div><div className="mt-5 space-y-4"><Step n="1" text="Buat project dan assign client di Invitations." done={Boolean(project)}/><Step n="2" text="Catat Project ID dan WordPress Post ID." done={Boolean(project?.wordpressPostId)}/><Step n="3" text="Upload plugin bridge ke WordPress dan aktifkan."/><Step n="4" text="Isi mapping post_id|project_id|form_id di Settings → Kykastory Bridge."/><Step n="5" text="Kirim RSVP percobaan lalu cek Webhook activity."/></div><Button className="mt-6 border border-stone-200" onClick={() => router.push("/admin/projects")}><ExternalLink size={14}/> Buka pengaturan project</Button></Card><Card className="p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Send size={18}/></div><div><h2 className="font-bold">Test endpoint</h2><p className="mt-1 text-xs text-stone-500">Gunakan data contoh sebelum WordPress aktif.</p></div></div><textarea className="mt-5 min-h-32 w-full rounded-xl border border-stone-200 p-3 font-mono text-xs" value={payload} onChange={e => setPayload(e.target.value)}/><Button disabled={!selected} className="mt-4 bg-ink text-white" onClick={() => void testSync()}><Send size={15}/> Kirim test RSVP</Button>{notice && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700">{notice}</p>}</Card></div>
    <Card className="mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-stone-100 p-5"><div><h2 className="text-sm font-bold">Webhook activity</h2><p className="mt-1 text-xs text-stone-500">Riwayat request project terpilih, refresh otomatis 30 detik.</p></div><Button className="h-8 px-3 text-xs text-stone-500" onClick={() => void loadLogs()}><RefreshCw size={13}/> Refresh</Button></div>{projectLogs.length ? <div className="divide-y divide-stone-100">{projectLogs.map(log => <div className="flex flex-col gap-2 p-4 text-sm sm:flex-row sm:items-center" key={log.id}><Badge tone={log.status === "SUCCESS" ? "green" : "red"}>{log.status}</Badge><span className="font-semibold">{log.source}</span><span className="text-stone-500">{log.message} · {log.imported} RSVP</span><span className="text-xs text-stone-400 sm:ml-auto">{new Date(log.createdAt).toLocaleString("id-ID")}</span></div>)}</div> : <div className="p-8 text-center text-sm text-stone-500">Belum ada webhook untuk project ini.</div>}</Card></AdminShell>;
}
function InfoRow({ label, value, tone }: { label: string; value: string; tone?: "green" }) { return <div className="flex items-center justify-between border-b border-stone-100 pb-3 text-sm"><span className="text-stone-500">{label}</span>{tone ? <Badge tone="green">{value}</Badge> : <span className="font-semibold">{value}</span>}</div>; }
function Step({ n, text, done }: { n: string; text: string; done?: boolean }) { return <div className="flex items-start gap-3"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold ${done ? "bg-emerald-100 text-emerald-700" : "bg-stone-100 text-stone-500"}`}>{done ? <Check size={13}/> : n}</span><p className="text-sm leading-6 text-stone-600">{text}</p></div>; }
