"use client";
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { Copy, Download, MessageSquareText, Plus, Save, Search, Send, Trash2, Upload, X } from "lucide-react";
import { Button, Card, Input, Badge } from "../../../components/ui";
import { guests as initial } from "../../../lib/mock-data";
import { Guest } from "../../../lib/types";

const defaultMessage = "Halo {{guest_name}}, kami mengundangmu ke pernikahan {{couple_name}}.\n\nBuka undangan: {{invitation_url}}\n\nTerima kasih.";

export default function Guests() {
  const [data, setData] = useState<Guest[]>(initial), [query, setQuery] = useState(""), [show, setShow] = useState(false), [name, setName] = useState(""), [phone, setPhone] = useState(""), [notice, setNotice] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const [message, setMessage] = useState(defaultMessage), [messageOpen, setMessageOpen] = useState(true), [saved, setSaved] = useState(false);
  useEffect(() => { fetch("/api/projects/demo-project/guests").then(r => r.json()).then(r => r.data?.length && setData(r.data)); fetch("/api/projects/demo-project/templates").then(r => r.json()).then(r => r.data?.[0]?.content && setMessage(r.data[0].content)); }, []);
  const filtered = useMemo(() => data.filter(g => g.name.toLowerCase().includes(query.toLowerCase()) || g.phone.includes(query)), [data, query]);
  const add = async () => { if (!name.trim() || !phone.trim()) { setNotice("Nama dan nomor WhatsApp wajib diisi."); return; } const response = await fetch("/api/projects/demo-project/guests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, phone, category: "Teman", seatCount: 1 }) }); const result = await response.json(); if (result.data) { setData([result.data, ...data]); setNotice("Tamu berhasil ditambahkan."); } else setNotice(result.error || "Tamu gagal ditambahkan."); setName(""); setPhone(""); setShow(false); };
  const exportCsv = (rows: Guest[], filename: string) => { const csv = ["Nama,Telepon,Kategori,Status", ...rows.map(g => [g.name, g.phone, g.category, g.deliveryStatus].map(v => `"${String(v).replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); setNotice("CSV berhasil diunduh."); };
  const importCsv = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const lines = (await file.text()).split(/\r?\n/).filter(Boolean).slice(1); let added = 0; for (const line of lines) { const [csvName, csvPhone] = line.split(",").map(value => value.replace(/^"|"$/g, "").trim()); if (!csvName || !csvPhone) continue; const response = await fetch("/api/projects/demo-project/guests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: csvName, phone: csvPhone, category: "Teman", seatCount: 1 }) }); const result = await response.json(); if (result.data) { setData(current => [result.data, ...current]); added++; } } setNotice(`${added} tamu berhasil diimport.`); event.target.value = ""; };
  const remove = async (id: number) => { if (!window.confirm("Hapus tamu ini?")) return; const response = await fetch(`/api/projects/demo-project/guests?id=${id}`, { method: "DELETE" }); if (response.ok) { setData(current => current.filter(g => g.id !== id)); setNotice("Tamu dihapus."); } };
  const personalized = (guest: Guest) => message.replaceAll("{{guest_name}}", guest.name).replaceAll("{{couple_name}}", "Chika & Fariz").replaceAll("{{invitation_url}}", `https://kykastory.com/chika-fariz?to=${guest.slug}`);
  const saveMessage = async () => { await fetch("/api/projects/demo-project/templates", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Undangan pernikahan", content: message }) }); setSaved(true); setTimeout(() => setSaved(false), 2500); };
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Guest management</p><h1 className="mt-2 font-display text-4xl">Tamu undangan</h1><p className="mt-2 text-sm text-stone-500">Kelola daftar tamu dan bagikan undangan personal.</p></div><div className="flex gap-2"><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={importCsv}/><Button className="border border-stone-200 bg-white" onClick={() => fileRef.current?.click()}><Upload size={15}/> Import CSV</Button><Button className="bg-ink text-white" onClick={() => { setNotice(""); setShow(true); }}><Plus size={16}/> Tambah tamu</Button></div></div>{notice && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700">{notice}</p>}
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Small label="Total tamu" value={data.length}/><Small label="Sudah terkirim" value={data.filter(g => g.deliveryStatus === "SENT").length} tone="green"/><Small label="Belum terkirim" value={data.filter(g => g.deliveryStatus === "NOT_SENT").length} tone="orange"/></div>
    <Card className="mt-6 overflow-hidden"><button onClick={() => setMessageOpen(!messageOpen)} className="flex w-full items-center gap-4 p-5 text-left"><div className="rounded-xl bg-sand p-2.5 text-gold"><MessageSquareText size={18}/></div><div className="flex-1"><p className="text-sm font-bold">Pesan share undangan</p><p className="mt-1 text-xs text-stone-500">Pesan ini dipersonalisasi otomatis untuk setiap tamu.</p></div><span className="text-xs font-bold text-gold">{messageOpen ? "Tutup" : "Ubah pesan"}</span></button>{messageOpen && <div className="border-t border-stone-100 p-5"><textarea className="min-h-[132px] w-full rounded-xl border border-stone-200 p-4 text-sm leading-6 outline-none focus:border-stone-500" value={message} onChange={e => { setMessage(e.target.value); setSaved(false); }}/><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-stone-400"><span>Variabel:</span>{["guest_name", "couple_name", "invitation_url"].map(v => <button key={v} onClick={() => setMessage(message + ` {{${v}}}`)} className="rounded-md bg-stone-100 px-2 py-1 font-semibold text-stone-600">&#123;&#123;{v}&#125;&#125;</button>)}<Button className="ml-auto h-8 bg-ink px-3 text-white" onClick={saveMessage}><Save size={14}/>{saved ? "Tersimpan" : "Simpan pesan"}</Button></div></div>}</Card>
    <Card className="mt-4 overflow-hidden"><div className="flex flex-col gap-3 border-b border-stone-100 p-5 md:flex-row md:items-center md:justify-between"><div className="relative max-w-sm flex-1"><Search size={16} className="absolute left-3 top-3 text-stone-400"/><Input className="pl-9" placeholder="Cari nama atau nomor HP..." value={query} onChange={e => setQuery(e.target.value)}/></div><Button className="border border-stone-200 bg-white text-stone-600" onClick={() => exportCsv(filtered, "kykastory-guests.csv")}><Download size={15}/> Export CSV</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-stone-50 text-[11px] uppercase tracking-wider text-stone-400"><tr><th className="px-5 py-4">Nama tamu</th><th className="px-5 py-4">No. HP</th><th className="px-5 py-4">Kategori</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Aksi</th></tr></thead><tbody>{filtered.map(g => <tr className="border-t border-stone-100" key={g.id}><td className="px-5 py-4 font-semibold">{g.name}</td><td className="px-5 py-4 text-stone-500">+{g.phone}</td><td className="px-5 py-4 text-stone-500">{g.category}</td><td className="px-5 py-4"><Badge tone={g.deliveryStatus === "SENT" ? "green" : "orange"}>{g.deliveryStatus === "SENT" ? "Terkirim" : "Belum terkirim"}</Badge></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button className="h-8 px-2 text-stone-500" title="WhatsApp" onClick={() => { window.open(`https://wa.me/${g.phone}?text=${encodeURIComponent(personalized(g))}`); setData(data.map(x => x.id === g.id ? { ...x, deliveryStatus: "SENT" } : x)); }}><Send size={15}/></Button><Button className="h-8 px-2 text-stone-500" onClick={() => { navigator.clipboard?.writeText(`https://kykastory.com/chika-fariz?to=${g.slug}`); setNotice("Link undangan disalin."); }}><Copy size={15}/></Button><Button className="h-8 px-2 text-stone-400" onClick={() => void remove(g.id)}><Trash2 size={15}/></Button></div></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-12 text-center text-sm text-stone-500">Belum ada tamu yang cocok.</div>}</div></Card>
    {show && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-5"><Card className="w-full max-w-md p-6"><div className="flex justify-between"><h2 className="font-display text-2xl">Tambah tamu</h2><button onClick={() => setShow(false)}><X size={18}/></button></div><label className="mt-6 block text-sm font-semibold">Nama lengkap<Input className="mt-2" placeholder="Contoh: Aditya & Dewi" value={name} onChange={e => setName(e.target.value)}/></label><label className="mt-4 block text-sm font-semibold">Nomor WhatsApp<Input className="mt-2" placeholder="0812..." value={phone} onChange={e => setPhone(e.target.value)}/></label><div className="mt-6 flex justify-end gap-2"><Button className="border border-stone-200" onClick={() => setShow(false)}>Batal</Button><Button className="bg-ink text-white" onClick={() => void add()}>Simpan tamu</Button></div></Card></div>}</div>;
}
function Small({ label, value, tone }: { label: string; value: number; tone?: "green" | "orange" }) { return <Card className="p-5"><p className="text-xs text-stone-500">{label}</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-bold">{value}</p><Badge tone={tone || "neutral"}>{tone === "green" ? "75%" : ""}</Badge></div></Card>; }
